server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cafenawa
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

jwt:
  algorithm: HS256
  expireTime: 14400000
  refreshTime: 14400000
  headerKey: Authorization